"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-mjlx+*h_xo4afec+!l$%3^3ptzdwbd$vwkuex5y_5*vwhji+b1"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django_grapesjs',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'pagebuilder',
    'contact',
    
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'django.middleware.locale.LocaleMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.template.context_processors.i18n",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en"

LANGUAGES = [
    ('en', ('English')), # English
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default Jazzmin settings
JAZZMIN_SETTINGS = {
    "site_title": ("Dashboard"),
    "site_header": ("Dashboard"),
    "site_title_short": ("Dashboard"),
    "site_header_short": ("Dashboard"),
    "welcome_sign": ("Welcome to Dashboard"),
    "search_model": "auth.User",
    "site_logo": "images/Classera-Logo-Colored%201.png",
    
    "user_avatar": None,
    "topmenu_links": [
        {"name": ("Home"), "url": "/home/", "permissions": ["auth.view_user"]},
        
    ],
    "show_ui_builder": False,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [
        "auth.group",
        ],
    "related_modal_active": False,
    "custom_css": None,
    #custom js load admin.js , owl.js 
    "show_collapse": False,
    "open_my_account": False,
    "open_support": False,
}


#grapesjs settings accept scripts that exist in the html files

GRAPESJS_SETTINGS = {
   # allow javascript in the editor
    "allow_scripts": True,
    # allow styles in the editor
    "allow_styles": True,
    # enable the editor in the django admin
    "enable_in_admin": True,
    # enable the editor in the django admin
    "enable_in_editor": True,
    # enable the editor in the django admin
    "enable_in_visual_editor": True,
    # enable the editor in the django admin
    "enable_in_visual_editor_modal": True,
    # enable the editor in the django admin
    "enable_in_visual_editor_modal_default_open": True,
    # enable the editor in the django admin
    "enable_in_visual_editor_modal_position": "bottom right",
    # enable the editor in the django admin
    "enable_in_visual_editor_modal_size": "medium"
}



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# grapesjs settings for django-grapesjs to enable scripts to iframe
GRAPESJS_DEFAULT_MODELS_DATA = True


