# Generated by Django 5.0.6 on 2024-06-25 18:27

import django_grapesjs.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", django_grapesjs.models.fields.GrapesJsHtmlField()),
            ],
        ),
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    django_grapesjs.models.fields.GrapesJsHtmlField(
                        default='\n\n\n\n\n    <!-- Stylesheets -->\n    <link href="/static/css/bootstrap.css" rel="stylesheet" />\n    <link href="/static/css/icons.min.css" rel="stylesheet" />\n    <link href="/static/css/style.css" rel="stylesheet" />\n    <link href="/static/css/responsive.css" rel="stylesheet" />\n    <link rel="stylesheet" href="/static/css/style-rtl.css" />\n    <link\n      rel="shortcut icon"\n      href="/static/images/New/logoIcon.png"\n      type="image/x-icon"\n    />\n    <link rel="icon" href="/static/images/New/logoIcon.png" type="image/x-icon" />\n    <link rel="preconnect" href="https://fonts.googleapis.com" />\n    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />\n    <link\n      href="https://fonts.googleapis.com/css2?family=Tajawal:wght@200;300;400;500;700;800;900&display=swap"\n      rel="stylesheet"\n    />\n    <!-- Responsive -->\n    <meta http-equiv="X-UA-Compatible" content="IE=edge" />\n    <meta\n      name="viewport"\n      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"\n    />\n    <script\n      src="https://kit.fontawesome.com/7ecf8dac4e.js"\n      crossorigin="anonymous"\n    ></script>\n\n<!-- Main Header-->\n<header class="main-header header-style-two">\n    <div class="container">\n      <div class="topHeader">\n        <a href="#">العربية</a>\n        <a href="#" class="PhoneNumber"\n          ><img src="/static/images/New/PhoneHeader.svg" /> +201015252525</a\n        >\n      </div>\n      <div class="HeaderCOntent">\n        <div class="main-box clearfix">\n          <div class="logo-box">\n            <div class="logo">\n              <a href="index.html">\n                <img src="/static/images/New/logo.svg" />\n              </a>\n            </div>\n          </div>\n\n          <div class="nav-outer">\n            <!-- Main Menu -->\n            <nav class="main-menu navbar-expand-md navbar-light">\n              <div\n                class="collapse navbar-collapse clearfix"\n                id="navbarSupportedContent"\n              >\n                <ul class="navigation clearfix">\n                  <li class="current"><a href="index.html">Home</a></li>\n                  <li class=""><a href="about.html">About</a></li>\n                  <li class="dropdown">\n                    <a href="#">Projects</a>\n\n                    <div class="Megamenu">\n                      <div class="row">\n                        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">\n                          <div class="ProjectIyemMenu">\n                            <div class="ImageProject">\n                              <img src="/static/images/New/p_1.png" />\n                            </div>\n                            <div class="ProjDatta">\n                              <div class="forflex">\n                                <div class="DewscoverProject">\n                                  <a href="projectdetails.html"\n                                    >Discover The Project\n                                    <img\n                                      src="/static/images/New/ButtonArrowWhiteRight.png"\n                                  /></a>\n                                </div>\n                                <div class="MorDatat">\n                                  <h2>Lamar</h2>\n                                  <p>\n                                    Lamaara is a luxury residential\n                                    project, in the best lively location\n                                  </p>\n                                </div>\n                              </div>\n                            </div>\n                          </div>\n                        </div>\n                      </div>\n                    </div>\n                  </li>\n                  <li class=""><a href="Blog.html">Blogs</a></li>\n                  <li class=""><a href="jobs.html">Jobs</a></li>\n                  <li class=""><a href="contactUs.html">Contact</a></li>\n                </ul>\n              </div>\n            </nav>\n            <!-- Main Menu End-->\n\n            <div class="outer-box clearfix">\n              <div class="Otherlogo">\n                <div class="logo">\n                  <a href="index.html">\n                    <img src="/static/images/New/logo2.svg" />\n                  </a>\n                </div>\n              </div>\n              <!-- Btn box -->\n              <div class="btn-box no-touch">\n                <button class="nav-toggler"><span></span></button>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </header>\n  <!--End Main Header -->\n\n\n\n    <script src="/static/js/jquery.js"></script>\n    <script src="/static/js/popper.min.js"></script>\n    <script src="/static/js/bootstrap.min.js"></script>\n    <script src="/static/js/owl.js"></script>\n    <script src="/static/js/wow.js"></script>\n    <script src="/static/js/appear.js"></script>\n    <script src="/static/js/jquery.stellar.min.js"></script>\n    <script src="/static/js/jquery.fancybox.js"></script>\n    <script src="/static/js/mixitup.js"></script>\n    <script src="/static/js/jquery.mCustomScrollbar.concat.min.js"></script>\n    <script src="/static/js/swiper.min.js"></script>\n    <script src="/static/js/TweenMax.min.js"></script>\n    <script src="/static/js/script.js"></script>'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("meta_description", models.TextField()),
                ("meta_keywords", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField()),
                ("content", django_grapesjs.models.fields.GrapesJsHtmlField()),
            ],
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_text",
                    models.TextField(unique=True, verbose_name="Original Text"),
                ),
                (
                    "translated_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Arabic Translate"
                    ),
                ),
            ],
            options={
                "verbose_name": "Word Dictionary",
                "verbose_name_plural": "Words Dictionary",
                "ordering": ["-id"],
            },
        ),
    ]
