# Generated by Django 5.0.6 on 2024-07-06 09:26

import django_grapesjs.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pagebuilder", "0002_alter_footer_content_alter_header_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footer",
            name="content",
            field=django_grapesjs.models.fields.GrapesJsHtmlField(
                default='\n\n\n\n    <link rel="preconnect" href="https://fonts.googleapis.com" />\n    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />\n    <link\n      href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"\n      rel="stylesheet"\n    />\n    <link\n      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"\n      rel="stylesheet"\n      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"\n      crossorigin="anonymous"\n    />\n    \n    <link rel="stylesheet" href="/static/css/owl.carousel.min.css" />\n    <link rel="stylesheet" href="/static/css/style.css" />\n    <link rel="shortcut icon" href="/static/images/favico.png" type="image/x-icon" />    \n    \n<footer class="py-10 bg-black text-white">\n    <div class="container">\n      <div class="row g-4">\n        <div class="col-md-6 col-lg-3">\n          <div class="footer-card">\n            <div class="footer-icon">\n              <img src="/static/images/footer1.png" alt="icon" class="w-100" />\n            </div>\n            <h5>Location</h5>\n            <p>Al Jazira Club, Tower A, Abu Dhabi</p>\n          </div>\n        </div>\n        <div class="col-md-6 col-lg-3">\n          <div class="footer-card">\n            <div class="footer-icon">\n              <img src="/static/images/footer2.png" alt="icon" class="w-100" />\n            </div>\n            <h5>Email</h5>\n            <p>info@taqyeed.ae</p>\n          </div>\n        </div>\n        <div class="col-md-6 col-lg-3">\n          <div class="footer-card">\n            <div class="footer-icon">\n              <img src="/static/images/footer3.png" alt="icon" class="w-100" />\n            </div>\n            <h5>Phone</h5>\n            <p>800 TAQYEED (827 9333)</p>\n          </div>\n        </div>\n        <div class="col-md-6 col-lg-3">\n          <div class="footer-card">\n            <div class="footer-icon">\n              <img src="/static/images/footer4.png" alt="icon" class="w-100" />\n            </div>\n            <h5>Socials</h5>\n            <ul class="list-unstyled social-links d-flex">\n              <li>\n                <a href="#" class="px-2">\n                  <img src="/static/images/Facebook.png" alt="" />\n                </a>\n              </li>\n              <li>\n                <a href="#" class="px-2">\n                  <img src="/static/images/Instagram.png" alt="" />\n                </a>\n              </li>\n              <li>\n                <a href="#" class="px-2">\n                  <img src="/static/images/LinkedIn.png" alt="" />\n                </a>\n              </li>\n            </ul>\n          </div>\n        </div>\n      </div>\n\n      <div class="footer-nav">\n        <img src="/static/images/Classera-Logo-Colored%201%20copy.png" alt="" />\n\n        <ul class="list-unstyled d-none d-lg-flex">\n          <li>\n            <a href="#" class="text-white">Home</a>\n          </li>\n          <li>\n            <a href="#" class="text-white">About Us</a>\n          </li>\n          <li>\n            <a href="#" class="text-white">Services</a>\n          </li>\n          <li>\n            <a href="#" class="text-white">Testimonials</a>\n          </li>\n          <li>\n            <a href="#" class="text-white">Contact</a>\n          </li>\n        </ul>\n      </div>\n    </div>\n  </footer>\n  <div class="footer-end">\n    <p>© 2024 TAQYEED Electronic Services Center. All rights reserved.</p>\n  </div>\n\n\n\n\n<script\n      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"\n      integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"\n      crossorigin="anonymous"\n    ></script>\n    <script src="/static/js/jquery-3.7.1.slim.min.js"></script>\n    \n    <script src="/static/js/main.js"></script>\n'
            ),
        ),
        migrations.AlterField(
            model_name="header",
            name="content",
            field=django_grapesjs.models.fields.GrapesJsHtmlField(),
        ),
    ]
