# Generated by Django 5.0.6 on 2024-07-09 14:30

import django_grapesjs.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pagebuilder", "0004_alter_footer_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="pages",
            name="content_ar",
            field=django_grapesjs.models.fields.GrapesJsHtmlField(default=1),
            preserve_default=False,
        ),
    ]
