# Generated by Django 5.0.6 on 2024-07-13 07:55

import django_grapesjs.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pagebuilder", "0005_pages_content_ar"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Footer",
        ),
        migrations.DeleteModel(
            name="Header",
        ),
        migrations.DeleteModel(
            name="Translation",
        ),
        migrations.AlterField(
            model_name="pages",
            name="content_ar",
            field=django_grapesjs.models.fields.GrapesJsHtmlField(
                verbose_name="الصفحة باللغه العربية"
            ),
        ),
    ]
