# Generated by Django 5.0.6 on 2024-07-13 16:15

import django_grapesjs.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pagebuilder", "0006_delete_footer_delete_header_delete_translation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pages",
            name="canonical_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pages",
            name="meta_description_ar",
            field=models.TextField(default=1, verbose_name="Arabic Meta Description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pages",
            name="meta_keywords_ar",
            field=models.TextField(
                blank=True, null=True, verbose_name="Arabic Meta Keywords"
            ),
        ),
        migrations.AddField(
            model_name="pages",
            name="og_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pages",
            name="og_description_ar",
            field=models.TextField(
                blank=True, null=True, verbose_name="Arabic OG Description"
            ),
        ),
        migrations.AddField(
            model_name="pages",
            name="og_image",
            field=models.ImageField(blank=True, null=True, upload_to="og_images/"),
        ),
        migrations.AddField(
            model_name="pages",
            name="og_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pages",
            name="og_title_ar",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Arabic OG Title"
            ),
        ),
        migrations.AddField(
            model_name="pages",
            name="seo_title",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name="pages",
            name="seo_title_ar",
            field=models.CharField(
                blank=True, max_length=70, null=True, verbose_name="Arabic SEO Title"
            ),
        ),
        migrations.AddField(
            model_name="pages",
            name="title_ar",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Arabic Title"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pages",
            name="twitter_card",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pages",
            name="twitter_card_ar",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Arabic Twitter Card",
            ),
        ),
        migrations.AlterField(
            model_name="pages",
            name="content_ar",
            field=django_grapesjs.models.fields.GrapesJsHtmlField(
                verbose_name="Arabic Content"
            ),
        ),
        migrations.AlterField(
            model_name="pages",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
