# Generated by Django 5.0.6 on 2024-07-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pagebuilder", "0007_pages_canonical_url_pages_meta_description_ar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pages",
            name="favicon",
            field=models.ImageField(blank=True, null=True, upload_to="favicons/"),
        ),
        migrations.AddField(
            model_name="pages",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="icons/"),
        ),
    ]
