# Generated by Django 5.0.6 on 2024-07-13 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pagebuilder", "0008_pages_favicon_pages_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pages",
            name="icon",
        ),
    ]
