# Generated by Django 5.0.6 on 2024-08-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pagebuilder", "0009_remove_pages_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="pages",
            name="canonical_url_ar",
            field=models.URLField(blank=True, null=True),
        ),
    ]
